WITH STMT
AS
(
SELECT ID
	,CODE
	,NAME
	,DATE
	,ISNULL(DEBIT,0) AS DR
	,ISNULL(CREDIT,0) AS CR
	,SUM(ISNULL(DEBIT,0)-ISNULL(CREDIT,0)) OVER (
	ORDER BY DATE 
	ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
	) AS BALANCE FROM TransactionTable
	WHERE CODE ='00006'
)SELECT * FROM STMT WHERE DATE BETWEEN '2020-12-16' AND '2020-12-19'

SELECT * FROM TransactionTable