alter PROC USP_LEDGER
@Code Nvarchar(50),
@StartDate datetime,
@EndDate datetime

AS 

begin
WITH STMT
AS
(
SELECT ID
	,CODE
	,NAME
	,DATE
	,ISNULL(DEBIT,0) AS DR
	,ISNULL(CREDIT,0) AS CR
	,SUM(ISNULL(DEBIT,0)-ISNULL(CREDIT,0)) OVER (
	ORDER BY DATE 
	ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
	) AS BALANCE FROM TransactionTable
	WHERE CODE =@Code
)SELECT * FROM STMT WHERE DATE BETWEEN @StartDate AND @EndDate
end

exec USP_LEDGER '00006', '2020-12-16','2020-12-19'